from Indicators.CCI import CCI
from Indicators.Average_Movement import Average_Movement
from Indicators.MA import MA
import pandas as pd
from Indicators.BB import BB
from Indicators.MAX import High
from Indicators.MIN import Low

Point = 0.00001
data = pd.read_csv('D:\CSV_Data\EURUSD_1H.CSV')
data = data.join(MA(data, 5, 0))
data = data.join(MA(data, 5, 1))
data = data.join(MA(data, 10, 0))
data = data.join(MA(data, 10, 1))
data = data.join(MA(data, 20, 0))
data = data.join(MA(data, 20, 1))
data = data.join(MA(data, 50, 0))
data = data.join(MA(data, 50, 1))
data = data.join(MA(data, 100, 0))
data = data.join(MA(data, 100, 1))
data = data.join(CCI(data, 5, 0))
data = data.join(CCI(data, 5, 1))
data = data.join(CCI(data, 10, 0))
data = data.join(CCI(data, 10, 1))
data = data.join(CCI(data, 20, 0))
data = data.join(CCI(data, 20, 1))
data = data.join(CCI(data, 50, 0))
data = data.join(CCI(data, 50, 1))
data = data.join(CCI(data, 100, 0))
data = data.join(CCI(data, 100, 1))
high_sub1, high_val1 = High(data, 10)
low_sub1, low_val1 = Low(data, 10)
data = data.join(high_sub1)
data = data.join(high_val1)
data = data.join(low_sub1)
data = data.join(low_val1)
high_sub2, high_val2 = High(data, 20)
low_sub2, low_val2 = Low(data, 20)
data = data.join(high_sub2)
data = data.join(high_val2)
data = data.join(low_sub2)
data = data.join(low_val2)
high_sub3, high_val3 = High(data, 50)
low_sub3, low_val3 = Low(data, 50)
data = data.join(high_sub3)
data = data.join(high_val3)
data = data.join(low_sub3)
data = data.join(low_val3)
high_sub4, high_val4 = High(data, 100)
low_sub4, low_val4 = Low(data, 100)
data = data.join(high_sub4)
data = data.join(high_val4)
data = data.join(low_sub4)
data = data.join(low_val4)
b1_upper, b1_lower = BB(data, 10, 0)
b2_upper, b2_lower = BB(data, 20, 0)
b3_upper, b3_lower = BB(data, 50, 0)
b4_upper, b4_lower = BB(data, 100, 0)
data = data.join(b1_upper)
data = data.join(b1_lower)
data = data.join(b2_upper)
data = data.join(b2_lower)
data = data.join(b3_upper)
data = data.join(b3_lower)
data = data.join(b4_upper)
data = data.join(b4_lower)
data = data.join(Average_Movement(data, 1, 0, Point))
data = data.join(Average_Movement(data, 3, 0, Point))
data = data.join(Average_Movement(data, 5, 0, Point))
data = data.join(Average_Movement(data, 10, 0, Point))
data = data.join(Average_Movement(data, 50, 0, Point))
data = data.join(Average_Movement(data, 100, 0, Point))
data.to_csv('D:\CSV_Data\EURUSD_1H_FEATURE.CSV', index=None, float_format='%.5f')
